# Cleaning

#### NA's (or NaNs) as value
1. **Alley:** Type of alley access to property
2. **BsmtQual:** Evaluates the height of the basement
3. **BsmtCond:** Evaluates the general condition of the basement
4. **BsmtExposure:** Refers to walkout or garden level walls
5. **BsmtFinType1:** Rating of basement finished area
6. **BsmtFinType2:** Rating of basement finished area (if multiple types)*
7. **FireplaceQu:** Fireplace quality
8. **GarageType:** Garage location
9. **GarageFinish:** Interior finish of the garage
10. **GarageQual:** Garage quality
11. **GarageCond:** Garage condition
12. **PoolQC:** Pool quality (Biggest of the above)
13. **Fence:** Fence quality
14. **MiscFeature:** Miscellaneous feature not covered in other categories

##### The two below are listed as None in description, but NA in dataset
* MasVnrArea: Masonry veneer type
* MasVnrType: Masonry veneer area in square feet

##### Others
* LotFrontage: Maybe set to NA if there is no street connected to property?
* GarageYrBlt: Set to NA if the above Garage attributes are set as NA

* Electrical: Electrical system. There is only one property with a missing data in Electrical. At row 1381


In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import copy
%matplotlib inline

In [2]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
print(train.shape, test.shape, "total[0] =",test.shape[0]+train.shape[0])

(1460, 81) (1459, 80) total[0] = 2919


In [3]:
border = train.shape[0]
border

1460

In [4]:
DFc = pd.concat([train, test],ignore_index=True, sort=False)
DFc.shape

(2919, 81)

In [5]:
DFc.iloc[border-2:border+2, :]

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg   
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg   
1460  1461          20       RH         80.0    11622   Pave   NaN      Reg   
1461  1462          20       RL         81.0    14267   Pave   NaN      IR1   

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
1458         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1459         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1460         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
1461         Lvl    AllPub  ...        0    NaN    NaN        Gar2   12500   

     MoSold YrSold  SaleType  SaleCondition  SalePrice  
1458      4   2010        WD         Normal   142125.0  
1459      6   2008        WD         Normal   147500.0  
1460      6   2010        WD         Normal        NaN  
1461      6   2010        WD         Normal        NaN  

[4 rows x 81 columns]

In [6]:
DFc = DFc.drop(columns=['LotShape', 'GarageYrBlt'])

In [7]:
def summary_missing_data(data):
    total = data.isnull().sum().sort_values(ascending=False)
    percent = (data.isnull().sum()/data.isnull().count() * 100).sort_values(ascending=False)
    missing_data = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])
    return missing_data

In [8]:
missing_data = summary_missing_data(DFc)
print(missing_data)

               Total    Percent
PoolQC          2909  99.657417
MiscFeature     2814  96.402878
Alley           2721  93.216855
Fence           2348  80.438506
SalePrice       1459  49.982871
FireplaceQu     1420  48.646797
LotFrontage      486  16.649538
GarageQual       159   5.447071
GarageFinish     159   5.447071
GarageCond       159   5.447071
GarageType       157   5.378554
BsmtCond          82   2.809181
BsmtExposure      82   2.809181
BsmtQual          81   2.774923
BsmtFinType2      80   2.740665
BsmtFinType1      79   2.706406
MasVnrType        24   0.822199
MasVnrArea        23   0.787941
MSZoning           4   0.137033
Utilities          2   0.068517
Functional         2   0.068517
BsmtHalfBath       2   0.068517
BsmtFullBath       2   0.068517
GarageArea         1   0.034258
GarageCars         1   0.034258
SaleType           1   0.034258
BsmtFinSF1         1   0.034258
BsmtFinSF2         1   0.034258
BsmtUnfSF          1   0.034258
TotalBsmtSF        1   0.034258
...     

In [9]:
atts = pd.read_csv('attributes.csv')

In [10]:
for i in range(0, len(atts)):
    if atts.iloc[i]['Type']=='Categorical':
        col_name=atts.iloc[i]['Attribute']
        DFc[col_name].fillna('None', inplace=True)
        DFc=pd.get_dummies(DFc, columns=[col_name])

for value in ((missing_data[missing_data['Total'] < 50]).index):
    DFc = DFc.drop(DFc.loc[DFc[value].isnull()].index)
summary_missing_data(DFc,17)

In [11]:
summary_missing_data(DFc.drop(columns=['SalePrice'])).head(11)

Total    Percent
LotFrontage      486  16.649538
MasVnrArea        23   0.787941
BsmtHalfBath       2   0.068517
BsmtFullBath       2   0.068517
BsmtFinSF2         1   0.034258
GarageCars         1   0.034258
GarageArea         1   0.034258
TotalBsmtSF        1   0.034258
BsmtUnfSF          1   0.034258
BsmtFinSF1         1   0.034258
OverallQual_2      0   0.000000

In [12]:
DFc.LotFrontage

0        65.0
1        80.0
2        68.0
3        60.0
4        84.0
5        85.0
6        75.0
7         NaN
8        51.0
9        50.0
10       70.0
11       85.0
12        NaN
13       91.0
14        NaN
15       51.0
16        NaN
17       72.0
18       66.0
19       70.0
20      101.0
21       57.0
22       75.0
23       44.0
24        NaN
25      110.0
26       60.0
27       98.0
28       47.0
29       60.0
        ...  
2889     50.0
2890     75.0
2891     69.0
2892     50.0
2893     60.0
2894     41.0
2895     44.0
2896     69.0
2897     65.0
2898     70.0
2899    140.0
2900      NaN
2901      NaN
2902     95.0
2903     88.0
2904    125.0
2905     78.0
2906     41.0
2907     58.0
2908      NaN
2909     21.0
2910     21.0
2911     80.0
2912     21.0
2913     21.0
2914     21.0
2915     21.0
2916    160.0
2917     62.0
2918     74.0
Name: LotFrontage, Length: 2919, dtype: float64

#### Manually filled in some missing values with modes

In [13]:
DFc['LotFrontage'].fillna(float(DFc['LotFrontage'].mode()), inplace=True)
DFc['MasVnrArea'].fillna(float(DFc['MasVnrArea'].mode()), inplace=True)
DFc['BsmtFullBath'].fillna(float(DFc['BsmtFullBath'].mode()), inplace=True)
DFc['BsmtHalfBath'].fillna(float(DFc['BsmtHalfBath'].mode()), inplace=True)
DFc['BsmtUnfSF'].fillna(float(DFc['BsmtUnfSF'].mode()), inplace=True)
DFc['GarageArea'].fillna(float(DFc['GarageArea'].mode()), inplace=True)
DFc['TotalBsmtSF'].fillna(float(DFc['TotalBsmtSF'].mode()), inplace=True)
DFc['BsmtFinSF1'].fillna(float(DFc['BsmtFinSF1'].mode()), inplace=True)
DFc['BsmtFinSF2'].fillna(float(DFc['BsmtFinSF2'].mode()), inplace=True)
DFc['GarageCars'].fillna(float(DFc['GarageCars'].mode()), inplace=True)

In [14]:
summary_missing_data(DFc.drop(columns=['SalePrice'])).head(11)

Total  Percent
SaleCondition_Partial      0      0.0
HouseStyle_SFoyer          0      0.0
BldgType_Duplex            0      0.0
BldgType_Twnhs             0      0.0
BldgType_TwnhsE            0      0.0
HouseStyle_1.5Fin          0      0.0
HouseStyle_1.5Unf          0      0.0
HouseStyle_1Story          0      0.0
HouseStyle_2.5Fin          0      0.0
HouseStyle_2.5Unf          0      0.0
HouseStyle_2Story          0      0.0

In [15]:
categorical = [i for i in DFc.columns if DFc[i].dtype == 'O']
print('Categorical: ', categorical)

Categorical:  []


In [16]:
numerical = [i for i in DFc.columns if DFc[i].dtype != 'O']
print('numerical columns: ', len(numerical))

numerical columns:  376


In [17]:
discrete = []
for i in numerical:
    if len(DFc[i].unique()) < 25:
        #print(i, ' values: ', DFc[i].unique())
        discrete.append(i)
print('Discrete values less than 25: ', len(discrete))

Discrete values less than 25:  355


In [18]:
continuous = [i for i in numerical if i not in discrete and i not in ['Id', 'SalePrice']]
print('Continuous vars: ', len(continuous))

Continuous vars:  19


In [19]:
pd.set_option('display.max_columns', 500)
na_cols = [i for i in DFc.columns if DFc[i].isna().any()]
na_cols

['SalePrice']

In [20]:
for i in na_cols:
    print(i, ':', DFc[i].dtype)

SalePrice : float64


In [21]:
lot_mean = DFc.LotFrontage.mean()

In [22]:
DFc.LotFrontage = DFc.LotFrontage.fillna(value=lot_mean)

In [23]:
DFc.LotFrontage

0        65.0
1        80.0
2        68.0
3        60.0
4        84.0
5        85.0
6        75.0
7        60.0
8        51.0
9        50.0
10       70.0
11       85.0
12       60.0
13       91.0
14       60.0
15       51.0
16       60.0
17       72.0
18       66.0
19       70.0
20      101.0
21       57.0
22       75.0
23       44.0
24       60.0
25      110.0
26       60.0
27       98.0
28       47.0
29       60.0
        ...  
2889     50.0
2890     75.0
2891     69.0
2892     50.0
2893     60.0
2894     41.0
2895     44.0
2896     69.0
2897     65.0
2898     70.0
2899    140.0
2900     60.0
2901     60.0
2902     95.0
2903     88.0
2904    125.0
2905     78.0
2906     41.0
2907     58.0
2908     60.0
2909     21.0
2910     21.0
2911     80.0
2912     21.0
2913     21.0
2914     21.0
2915     21.0
2916    160.0
2917     62.0
2918     74.0
Name: LotFrontage, Length: 2919, dtype: float64

In [30]:
DFc['floors_SF'] =  (DFc['1stFlrSF']) + (DFc['2ndFlrSF'])

In [63]:
DFc.head()

Id  LotFrontage  LotArea  YearBuilt  YearRemodAdd  MasVnrArea  BsmtFinSF1  \
0   1         65.0     8450       2003          2003       196.0       706.0   
1   2         80.0     9600       1976          1976         0.0       978.0   
2   3         68.0    11250       2001          2002       162.0       486.0   
3   4         60.0     9550       1915          1970         0.0       216.0   
4   5         84.0    14260       2000          2000       350.0       655.0   

   BsmtFinSF2  BsmtUnfSF  TotalBsmtSF  1stFlrSF  2ndFlrSF  LowQualFinSF  \
0         0.0      150.0        856.0       856       854             0   
1         0.0      284.0       1262.0      1262         0             0   
2         0.0      434.0        920.0       920       866             0   
3         0.0      540.0        756.0       961       756             0   
4         0.0      490.0       1145.0      1145      1053             0   

   GrLivArea  BsmtFullBath  BsmtHalfBath  FullBath  HalfBath  BedroomAbvGr  \
0       1710           1.0           0.0         2         1             3   
1       1262           0.0           1.0         2         0             3   
2       1786           1.0           0.0         2         1             3   
3       1717           1.0           0.0         1         0             3   
4       2198           1.0           0.0         2         1             4   

   KitchenAbvGr  TotRmsAbvGrd  Fireplaces  GarageCars  GarageArea  WoodDeckSF  \
0             1             8           0         2.0       548.0           0   
1             1             6           1         2.0       460.0         298   
2             1             6           1         2.0       608.0           0   
3             1             7           1         3.0       642.0           0   
4             1             9           1         3.0       836.0         192   

   OpenPorchSF  EnclosedPorch  3SsnPorch  ScreenPorch  PoolArea  MoSold  \
0           61              0          0            0         0       2   
1            0              0          0            0         0       5   
2           42              0          0            0         0       9   
3           35            272          0            0         0       2   
4           84              0          0            0         0      12   

   YrSold  SalePrice  MSSubClass_20  MSSubClass_30  MSSubClass_40  \
0    2008   208500.0              0              0              0   
1    2007   181500.0              1              0              0   
2    2008   223500.0              0              0              0   
3    2006   140000.0              0              0              0   
4    2008   250000.0              0              0              0   

   MSSubClass_45  MSSubClass_50  MSSubClass_60  MSSubClass_70  MSSubClass_75  \
0              0              0              1              0              0   
1              0              0              0              0              0   
2              0              0              1              0              0   
3              0              0              0              1              0   
4              0              0              1              0              0   

   MSSubClass_80  MSSubClass_85  MSSubClass_90  MSSubClass_120  \
0              0              0              0               0   
1              0              0              0               0   
2              0              0              0               0   
3              0              0              0               0   
4              0              0              0               0   

   MSSubClass_150  MSSubClass_160  MSSubClass_180  MSSubClass_190  \
0               0               0               0               0   
1               0               0               0               0   
2               0               0               0               0   
3               0               0               0               0   
4               0         

In [66]:
DFc['TotalBath'] = DFc['BsmtFullBath'] + DFc['BsmtHalfBath'] + DFc['FullBath'] + DFc['HalfBath']

In [32]:
DFc['GarageScore'] = DFc['GarageCars'] * DFc['GarageArea']

In [36]:
DFc = DFc.drop(columns=['BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'YearBuilt', 'YearRemodAdd', 'LowQualFinSF', 'BsmtHalfBath', 'BsmtFullBath', 'FullBath', 'HalfBath', '1stFlrSF', '2ndFlrSF', 'GarageCars', 'GarageArea', 'ScreenPorch', '3SsnPorch', 'EnclosedPorch', 'OpenPorchSF', 'WoodDeckSF',   ])

In [37]:
DFc.head()

Id  LotFrontage  LotArea  MasVnrArea  TotalBsmtSF  GrLivArea  BedroomAbvGr  \
0   1         65.0     8450       196.0        856.0       1710             3   
1   2         80.0     9600         0.0       1262.0       1262             3   
2   3         68.0    11250       162.0        920.0       1786             3   
3   4         60.0     9550         0.0        756.0       1717             3   
4   5         84.0    14260       350.0       1145.0       2198             4   

   KitchenAbvGr  TotRmsAbvGrd  Fireplaces  PoolArea  MoSold  YrSold  \
0             1             8           0         0       2    2008   
1             1             6           1         0       5    2007   
2             1             6           1         0       9    2008   
3             1             7           1         0       2    2006   
4             1             9           1         0      12    2008   

   SalePrice  MSSubClass_20  MSSubClass_30  MSSubClass_40  MSSubClass_45  \
0   208500.0              0              0              0              0   
1   181500.0              1              0              0              0   
2   223500.0              0              0              0              0   
3   140000.0              0              0              0              0   
4   250000.0              0              0              0              0   

   MSSubClass_50  MSSubClass_60  MSSubClass_70  MSSubClass_75  MSSubClass_80  \
0              0              1              0              0              0   
1              0              0              0              0              0   
2              0              1              0              0              0   
3              0              0              1              0              0   
4              0              1              0              0              0   

   MSSubClass_85  MSSubClass_90  MSSubClass_120  MSSubClass_150  \
0              0              0               0               0   
1              0              0               0               0   
2              0              0               0               0   
3              0              0               0               0   
4              0              0               0               0   

   MSSubClass_160  MSSubClass_180  MSSubClass_190  MSZoning_C (all)  \
0               0               0               0                 0   
1               0               0               0                 0   
2               0               0               0                 0   
3               0               0               0                 0   
4               0               0               0                 0   

   MSZoning_FV  MSZoning_None  MSZoning_RH  MSZoning_RL  MSZoning_RM  \
0            0              0            0            1            0   
1            0              0            0            1            0   
2            0              0            0            1            0   
3            0              0            0            1            0   
4            0              0            0            1            0   

   Street_Grvl  Street_Pave  Alley_Grvl  Alley_None  Alley_Pave  \
0            0            1           0           1           0   
1            0            1           0           1           0   
2            0            1           0           1           0   
3            0            1           0           1           0   
4            0            1           0           1           0   

   LandContour_Bnk  LandContour_HLS  LandContour_Low  LandContour_Lvl  \
0                0                0                0                1   
1                0                0                0                1   
2                0                0                0                1   
3                0                0                0                1   
4                0                0                0                1   

   Utilities_AllPub  Utilities_NoSeWa  Utiliti

In [58]:
DFc.TotalBsmtSF.head()

0     856.0
1    1262.0
2     920.0
3     756.0
4    1145.0
Name: TotalBsmtSF, dtype: float64

In [38]:
DFtrain = DFc.iloc[0:border,:]
print(DFtrain.shape)
DFtest = DFc.iloc[border:,:]
DFtest = DFtest.drop(columns=['SalePrice'])
print(DFtest.shape)

(1460, 360)
(1459, 359)


In [39]:
DFtrain.to_csv('trainer.csv', index=False)
DFtest.to_csv('tester.csv', index=False)

# Modeling

Was going to get ready for PCA stuff below

In [40]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [41]:
X = DFtrain.drop(columns=['Id', 'SalePrice'])
Y = DFtrain['SalePrice']
Xt = DFtest.drop(columns=['Id'])

##### Scaling, otherwise we will just see one component!

In [42]:
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)
Xt = scaler.transform(Xt)

In [43]:
Xcopy  = X
Ycopy  = Y
Xtcopy = Xt

In [44]:
pca = PCA(5)

In [45]:
pca.fit(X)

PCA(copy=True, iterated_power='auto', n_components=5, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [46]:
pca.n_components_

5

In [47]:
X = pca.transform(X)
Xt = pca.transform(Xt)

In [48]:
X.shape, Xt.shape, Y.shape

((1460, 5), (1459, 5), (1460,))

## Linear Regression

In [49]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [50]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [51]:
XTRAIN, XTEST, YTRAIN, YTEST=train_test_split(X,Y)
r=LinearRegression().fit(XTRAIN,YTRAIN)
P=r.predict(XTEST)
R2=r2_score(YTEST,P)
MSE = mean_squared_error(YTEST,P)
print(R2,MSE)

0.6623786541998546 1711517549.9529085


In [52]:
errs=[]
for i in range(100):
    XTRAIN, XTEST, YTRAIN, YTEST=train_test_split(X,Y)
    r=LinearRegression().fit(XTRAIN,YTRAIN)
    P=r.predict(XTEST)
    R2=r2_score(YTEST,P)
    #MSE = mean_squared_error(YTEST,P)
    #print(R2,MSE)
    errs.append(1-R2)

In [53]:
print('Result: ~',np.round((1-np.mean(errs))*100), '% accuracy')

Result: ~ 76.0 % accuracy


maybe we should try a different number of components

## Naive Bayes

In [54]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score,confusion_matrix

In [55]:
gnb=GaussianNB()
errs=[]
nsplits = 100 #it takes a very long time with 100 splits
for split in range(nsplits):
    XTRAIN, XTEST, YTRAIN, YTEST=train_test_split(X,Y,test_size=.25)
    gnb.fit(XTRAIN,YTRAIN)
    YP=gnb.predict(XTEST)
    errs.append(1-accuracy_score(YTEST,YP))
print("%d Splits: Mean Error=%7.6f +/- %7.6f (95%%)"\
      %(nsplits, np.mean(errs),1.96*np.std(errs)))
print(confusion_matrix(YTEST,YP))

100 Splits: Mean Error=0.991205 +/- 0.009615 (95%)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


## Random Forest

In [56]:
from sklearn.ensemble import RandomForestClassifier

In [57]:
RF=RandomForestClassifier(n_estimators=500)
XTRAIN, XTEST, YTRAIN, YTEST=train_test_split(Xcopy,Ycopy,test_size=.25)
RF.fit(XTRAIN,YTRAIN)
YP=RF.predict(XTEST)
error=(1-accuracy_score(YTEST,YP))
print('Error: ', error*100,'%')

Error:  98.63013698630137 %


## Logistic Regression

In [58]:
from sklearn.linear_model import LogisticRegression
logisticRegr = LogisticRegression(solver = 'lbfgs')
logisticRegr.fit(X,Y)

/home/marcello/data_science/python_projects/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [59]:
logisticRegr.predict(Xt[0].reshape(1,-1))

array([135000.])

In [69]:
final_predictions = logisticRegr.predict(Xt)

In [87]:
test.Id

0       1461
1       1462
2       1463
3       1464
4       1465
5       1466
6       1467
7       1468
8       1469
9       1470
10      1471
11      1472
12      1473
13      1474
14      1475
15      1476
16      1477
17      1478
18      1479
19      1480
20      1481
21      1482
22      1483
23      1484
24      1485
25      1486
26      1487
27      1488
28      1489
29      1490
        ... 
1429    2890
1430    2891
1431    2892
1432    2893
1433    2894
1434    2895
1435    2896
1436    2897
1437    2898
1438    2899
1439    2900
1440    2901
1441    2902
1442    2903
1443    2904
1444    2905
1445    2906
1446    2907
1447    2908
1448    2909
1449    2910
1450    2911
1451    2912
1452    2913
1453    2914
1454    2915
1455    2916
1456    2917
1457    2918
1458    2919
Name: Id, Length: 1459, dtype: int64

In [84]:
len(final_predictions)

1459

In [88]:
output = pd.DataFrame({'Id': test.Id, 'SalePrice':final_predictions})

In [89]:
output.to_csv('submission.csv', index=False)